-- L'escale Créole : descriptifs « recette » (ingrédients + grandes étapes + secret du chef) — 2026-10-08.
-- Textes validés par le porteur du projet, rédigés d'après des recettes réunionnaises / malgaches
-- de référence ; « le secret du chef » couvre ce qui varie d'une cuisine à l'autre. FR + EN + IT.
-- (Le rougail saucisses a sa propre migration, escale_creole_descriptif_rougail.)

create temp table _desc (nom text, fr text, en text, it text) on commit drop;
insert into _desc values
  ('Massalé cabri', 'Cabri, massalé (le mélange d''épices réunionnais), oignons, ail, gingembre, curcuma, une pointe de piment (ou pas, selon ton choix)… et le secret du chef. Le cabri est coupé en morceaux, doré avec les oignons, l''ail et le gingembre pilés, puis enrobé de massalé. On mouille à hauteur et on laisse mijoter longuement à feu doux, jusqu''à une viande fondante dans une sauce bien épicée. Servi avec du riz.', 'Goat, massalé (Réunion''s spice blend), onions, garlic, ginger, turmeric, a touch of chili (or not, your choice)… and the chef''s secret. The goat is cut into pieces, browned with the onions and pounded garlic and ginger, then coated in massalé. Covered with water, it simmers slowly over low heat until the meat is meltingly tender in a richly spiced sauce. Served with rice.', 'Capretto, massalé (la miscela di spezie della Riunione), cipolle, aglio, zenzero, curcuma, un pizzico di peperoncino (o no, a tua scelta)… e il segreto dello chef. Il capretto viene tagliato a pezzi, rosolato con le cipolle e con aglio e zenzero pestati, poi avvolto nel massalé. Coperto d''acqua, cuoce a lungo a fuoco lento fino a diventare tenerissimo in un sugo ben speziato. Servito con riso.'),
  ('Rôti porc à la créole', 'Rôti de porc, ail, gingembre, oignons, thym, une pointe de piment (ou pas, selon ton choix)… et le secret du chef. La viande est frottée à l''ail et au gingembre pilés, saisie sur toutes ses faces en cocotte, puis cuite à couvert à feu doux avec les oignons et le thym jusqu''à ce qu''elle soit bien tendre. Servi en tranches avec sa sauce et du riz.', 'Pork roast, garlic, ginger, onions, thyme, a touch of chili (or not, your choice)… and the chef''s secret. The meat is rubbed with pounded garlic and ginger, seared on all sides in a pot, then cooked covered over low heat with the onions and thyme until very tender. Served sliced with its sauce and rice.', 'Arrosto di maiale, aglio, zenzero, cipolle, timo, un pizzico di peperoncino (o no, a tua scelta)… e il segreto dello chef. La carne viene strofinata con aglio e zenzero pestati, rosolata su tutti i lati in casseruola, poi cotta coperta a fuoco lento con cipolle e timo finché è ben tenera. Servito a fette con il suo sugo e riso.'),
  ('Sauté porc aux gros piments', 'Porc, gros piments (doux et parfumés, pas brûlants), oignons, ail, gingembre… et le secret du chef. Le porc est d''abord doré à la marmite avec l''ail et le gingembre, puis on ajoute les oignons et les gros piments en lanières, et on laisse mijoter jusqu''à ce que la viande soit tendre. Servi avec du riz.', 'Pork, large peppers (mild and fragrant, not fiery), onions, garlic, ginger… and the chef''s secret. The pork is first browned in the pot with garlic and ginger, then the onions and sliced large peppers go in, and it simmers until the meat is tender. Served with rice.', 'Maiale, peperoni grossi (dolci e profumati, non piccanti), cipolle, aglio, zenzero… e il segreto dello chef. Il maiale viene prima rosolato in pentola con aglio e zenzero, poi si aggiungono le cipolle e i peperoni a listarelle e si lascia sobbollire finché la carne è tenera. Servito con riso.'),
  ('Poisson frit entier', 'Carangue entière, ail, citron, sel, poivre… et le secret du chef. Le poisson est vidé, entaillé et mariné, puis frit entier jusqu''à avoir une peau croustillante et une chair moelleuse. Servi avec du riz et une pointe de piment (ou pas, selon ton choix).', 'Whole trevally, garlic, lemon, salt, pepper… and the chef''s secret. The fish is cleaned, scored and marinated, then fried whole until the skin is crisp and the flesh tender. Served with rice and a touch of chili (or not, your choice).', 'Carangide intero, aglio, limone, sale, pepe… e il segreto dello chef. Il pesce viene pulito, inciso e marinato, poi fritto intero fino ad avere la pelle croccante e la carne morbida. Servito con riso e un pizzico di peperoncino (o no, a tua scelta).'),
  ('Bol renversé poulet ou zébu', 'Œuf au plat, poulet ou zébu et légumes sautés au wok en sauce soja et huître, riz blanc… et le secret du chef. Tout est tassé à l''envers dans un bol (l''œuf au fond, puis la viande et les légumes, puis le riz), et le bol est retourné sur l''assiette au moment de servir. Un classique né dans la communauté chinoise de La Réunion et de Maurice.', 'Fried egg, chicken or zebu and vegetables stir-fried in soy and oyster sauce, white rice… and the chef''s secret. Everything is packed upside down in a bowl (egg at the bottom, then meat and vegetables, then rice), and the bowl is flipped onto the plate when served. A classic born in the Chinese communities of Réunion and Mauritius.', 'Uovo all''occhio di bue, pollo o zebù e verdure saltati al wok in salsa di soia e d''ostrica, riso bianco… e il segreto dello chef. Tutto viene pressato a rovescio in una ciotola (l''uovo sul fondo, poi carne e verdure, poi il riso) e la ciotola si capovolge sul piatto al momento di servire. Un classico nato nella comunità cinese della Riunione e di Mauritius.'),
  ('Riz frit poulet ou zébu', 'Riz, poulet ou zébu, œuf, oignon, petits légumes, sauce soja… et le secret du chef. Le riz est sauté à feu vif au wok avec l''œuf brouillé, la viande et les légumes, puis relevé à la sauce soja.', 'Rice, chicken or zebu, egg, onion, vegetables, soy sauce… and the chef''s secret. The rice is stir-fried over high heat in a wok with scrambled egg, the meat and vegetables, then seasoned with soy sauce.', 'Riso, pollo o zebù, uovo, cipolla, verdurine, salsa di soia… e il segreto dello chef. Il riso viene saltato a fuoco vivo nel wok con uovo strapazzato, carne e verdure, poi insaporito con salsa di soia.'),
  ('Bouchon porc', 'Pâte fine farcie de porc haché assaisonné… et le secret du chef. Les bouchons sont façonnés à la main et cuits à la vapeur. À tremper dans la sauce soja, avec ou sans piment.', 'Thin dough filled with seasoned minced pork… and the chef''s secret. The bouchons are shaped by hand and steamed. Dip them in soy sauce, with or without chili.', 'Pasta sottile ripiena di carne di maiale tritata e condita… e il segreto dello chef. I bouchons sono modellati a mano e cotti al vapore. Da intingere nella salsa di soia, con o senza peperoncino.'),
  ('Sambos zébu ou poulet', 'Pâte fine pliée en triangle, garnie de zébu ou de poulet haché, revenu avec oignon, ail et épices… et le secret du chef. Frits jusqu''à être bien dorés et croustillants.', 'Thin pastry folded into a triangle, filled with minced zebu or chicken cooked with onion, garlic and spices… and the chef''s secret. Fried until golden and crisp.', 'Pasta sottile piegata a triangolo, ripiena di zebù o pollo tritato, rosolato con cipolla, aglio e spezie… e il segreto dello chef. Fritti fino a diventare dorati e croccanti.'),
  ('Sambos fromage', 'Pâte fine pliée en triangle, garnie de fromage fondant… et le secret du chef. Frits jusqu''à être bien dorés et croustillants.', 'Thin pastry folded into a triangle, filled with melting cheese… and the chef''s secret. Fried until golden and crisp.', 'Pasta sottile piegata a triangolo, ripiena di formaggio filante… e il segreto dello chef. Fritti fino a diventare dorati e croccanti.'),
  ('Demi-lune poulet', 'Pâte fine pliée en demi-lune, garnie de poulet haché revenu avec oignon, ail et épices… et le secret du chef. Frites jusqu''à être bien dorées et croustillantes.', 'Thin pastry folded into a half-moon, filled with minced chicken cooked with onion, garlic and spices… and the chef''s secret. Fried until golden and crisp.', 'Pasta sottile piegata a mezzaluna, ripiena di pollo tritato rosolato con cipolla, aglio e spezie… e il segreto dello chef. Fritte fino a diventare dorate e croccanti.'),
  ('Soupe chinoise', 'Bouillon parfumé au gingembre, nouilles chinoises, viande, légumes, œuf, ciboule… et le secret du chef. Le bouillon mijote longuement avec ses aromates, puis on y ajoute les nouilles, la garniture et les légumes juste avant de servir, bien chaud. La grande soupe des gargotes chinoises de Madagascar.', 'Ginger-scented broth, Chinese noodles, meat, vegetables, egg, spring onion… and the chef''s secret. The broth simmers slowly with its aromatics, then the noodles, toppings and vegetables are added just before serving piping hot. The big noodle soup of Madagascar''s Chinese eateries.', 'Brodo profumato allo zenzero, noodles cinesi, carne, verdure, uovo, cipollotto… e il segreto dello chef. Il brodo sobbolle a lungo con i suoi aromi, poi si aggiungono noodles, guarnizione e verdure appena prima di servire, bollente. La grande zuppa delle trattorie cinesi del Madagascar.'),
  ('Émincé de poulet au brède chinois', 'Fines lamelles de poulet, brède chinois, ail… et le secret du chef. La viande est saisie à feu vif au wok, puis les brèdes sont ajoutées juste le temps qu''elles tombent, pour rester croquantes. Servi avec du riz.', 'Thin strips of chicken, Chinese greens, garlic… and the chef''s secret. The meat is seared over high heat in a wok, then the greens are added just long enough to wilt, so they stay crunchy. Served with rice.', 'Straccetti di pollo, verdure cinesi, aglio… e il segreto dello chef. La carne viene saltata a fuoco vivo nel wok, poi si aggiungono le verdure giusto il tempo di appassire, così restano croccanti. Servito con riso.'),
  ('Émincé de zébu au brède chinois', 'Fines lamelles de zébu, brède chinois, ail… et le secret du chef. La viande est saisie à feu vif au wok, puis les brèdes sont ajoutées juste le temps qu''elles tombent, pour rester croquantes. Servi avec du riz.', 'Thin strips of zebu, Chinese greens, garlic… and the chef''s secret. The meat is seared over high heat in a wok, then the greens are added just long enough to wilt, so they stay crunchy. Served with rice.', 'Straccetti di zebù, verdure cinesi, aglio… e il segreto dello chef. La carne viene saltata a fuoco vivo nel wok, poi si aggiungono le verdure giusto il tempo di appassire, così restano croccanti. Servito con riso.'),
  ('Émincé de poulet au poivre vert', 'Fines lamelles de poulet, poivre vert de Madagascar, crème… et le secret du chef. La viande est saisie à feu vif, puis nappée d''une sauce réduite aux grains de poivre vert. Servi avec du riz.', 'Thin strips of chicken, Madagascar green pepper, cream… and the chef''s secret. The meat is seared over high heat, then coated in a reduced green peppercorn sauce. Served with rice.', 'Straccetti di pollo, pepe verde del Madagascar, panna… e il segreto dello chef. La carne viene scottata a fuoco vivo, poi nappata con una salsa ristretta ai grani di pepe verde. Servito con riso.'),
  ('Émincé de zébu au poivre vert', 'Fines lamelles de zébu, poivre vert de Madagascar, crème… et le secret du chef. La viande est saisie à feu vif, puis nappée d''une sauce réduite aux grains de poivre vert. Servi avec du riz.', 'Thin strips of zebu, Madagascar green pepper, cream… and the chef''s secret. The meat is seared over high heat, then coated in a reduced green peppercorn sauce. Served with rice.', 'Straccetti di zebù, pepe verde del Madagascar, panna… e il segreto dello chef. La carne viene scottata a fuoco vivo, poi nappata con una salsa ristretta ai grani di pepe verde. Servito con riso.'),
  ('Émincé de poulet aux oignons', 'Fines lamelles de poulet, oignons, ail… et le secret du chef. Les oignons sont dorés doucement jusqu''à devenir fondants, puis la viande est saisie à feu vif et le tout lié d''une sauce. Servi avec du riz.', 'Thin strips of chicken, onions, garlic… and the chef''s secret. The onions are gently browned until soft, then the meat is seared over high heat and everything is bound in a sauce. Served with rice.', 'Straccetti di pollo, cipolle, aglio… e il segreto dello chef. Le cipolle vengono dorate dolcemente finché diventano morbide, poi la carne viene saltata a fuoco vivo e il tutto legato con una salsa. Servito con riso.'),
  ('Émincé de zébu aux oignons', 'Fines lamelles de zébu, oignons, ail… et le secret du chef. Les oignons sont dorés doucement jusqu''à devenir fondants, puis la viande est saisie à feu vif et le tout lié d''une sauce. Servi avec du riz.', 'Thin strips of zebu, onions, garlic… and the chef''s secret. The onions are gently browned until soft, then the meat is seared over high heat and everything is bound in a sauce. Served with rice.', 'Straccetti di zebù, cipolle, aglio… e il segreto dello chef. Le cipolle vengono dorate dolcemente finché diventano morbide, poi la carne viene saltata a fuoco vivo e il tutto legato con una salsa. Servito con riso.'),
  ('Émincé de poulet au gingembre', 'Fines lamelles de poulet, gingembre frais en julienne, ail… et le secret du chef. La viande est saisie à feu vif au wok avec le gingembre et l''ail, pour garder tout son parfum. Servi avec du riz.', 'Thin strips of chicken, fresh ginger julienne, garlic… and the chef''s secret. The meat is seared over high heat in a wok with the ginger and garlic to keep all its fragrance. Served with rice.', 'Straccetti di pollo, zenzero fresco a julienne, aglio… e il segreto dello chef. La carne viene saltata a fuoco vivo nel wok con zenzero e aglio, per conservarne tutto il profumo. Servito con riso.'),
  ('Émincé de zébu au gingembre', 'Fines lamelles de zébu, gingembre frais en julienne, ail… et le secret du chef. La viande est saisie à feu vif au wok avec le gingembre et l''ail, pour garder tout son parfum. Servi avec du riz.', 'Thin strips of zebu, fresh ginger julienne, garlic… and the chef''s secret. The meat is seared over high heat in a wok with the ginger and garlic to keep all its fragrance. Served with rice.', 'Straccetti di zebù, zenzero fresco a julienne, aglio… e il segreto dello chef. La carne viene saltata a fuoco vivo nel wok con zenzero e aglio, per conservarne tutto il profumo. Servito con riso.');

update public.products p set description = d.fr
  from _desc d
 where p.restaurant_id = '128e68ab-8e64-4f48-bf79-acc67f3deca9' and not p.is_archived and p.name = d.nom;

insert into public.traductions_catalogue (fr, langue, texte, source)
select fr, 'en', en, 'manuel' from _desc
union all
select fr, 'it', it, 'manuel' from _desc
on conflict (fr, langue) do nothing;
