-- PILOTAGE ADMIN — pouvoir AGIR pendant le service, pas seulement regarder.
-- (Applique en base le 2026-09-05 sous le nom `pilotage_admin_actions_et_journal`.)
--
-- Le tableau de bord affichait deja les commandes actives, mais l'administrateur
-- ne pouvait rien faire : `set_order_status` est reservee au PERSONNEL du
-- restaurant (`is_active_restaurant_staff_of`), et l'administrateur n'en fait
-- pas partie. Une commande bloquee un dimanche soir n'avait aucun recours.
--
-- Deux differences volontaires avec la version restaurant :
--   - l'administrateur peut forcer N'IMPORTE QUELLE transition, y compris en
--     arriere. C'est un outil de rattrapage : si la regle metier pouvait couvrir
--     le cas, le restaurant s'en serait deja charge ;
--   - toute action est JOURNALISEE dans `admin_actions`. Sur un litige avec un
--     restaurateur, savoir qui a change quoi et quand vaut plus cher que la
--     fonctionnalite elle-meme.
--
-- ⚠️ `admin_actions` n'a AUCUNE policy INSERT : le journal ne s'ecrit que par
-- les RPC, en SECURITY DEFINER. Un administrateur ne doit pas pouvoir fabriquer
-- une entree — un journal qu'on peut ecrire a la main ne prouve rien.
--
-- Contenu : table admin_actions + admin_set_order_status + admin_set_restaurant_open.

-- ---------------------------------------------------------------------------
-- Assignation manuelle d'un livreur (`admin_assign_courier`).
--
-- En fonctionnement normal, un livreur prend lui-meme une commande passee en
-- `en_livraison`. Il manquait le rattrapage : livreur qui accepte puis ne part
-- pas, telephone eteint, ou commande que personne ne prend un dimanche soir.
-- Sans ce geste, la seule issue etait d'annuler une commande valide.
--
-- ⚠️ On NE verifie PAS que le livreur est marque disponible — c'est deliberе :
-- l'usage principal de cette fonction est justement de rattraper une situation
-- ou l'etat declare ne correspond plus a la realite du terrain. Verifier la
-- disponibilite reviendrait a interdire l'outil au moment ou il sert.
--
-- On verifie en revanche que la personne est bien un livreur : assigner a un
-- uuid quelconque produirait une commande qui n'apparait sur l'ecran d'aucun
-- livreur, sans la moindre erreur visible.
--
-- p_courier_id a NULL = retirer l'assignation et remettre la commande dans la
-- file. Cela efface aussi `picked_up_at`, sinon la commande resterait marquee
-- « recuperee » par personne.
